# Generated by Django 6.0.5 on 2026-05-10 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='এড নাম')),
                ('ad_type', models.CharField(choices=[('popup', 'পপআপ'), ('banner', 'ব্যানার'), ('sidebar', 'সাইডবার'), ('inline', 'ইনলাইন')], default='banner', max_length=20)),
                ('placement', models.CharField(choices=[('all', 'সব জায়গায়'), ('home', 'শুধু হোম পেজ'), ('helpers', 'হেল্পার পেজ'), ('detail', 'হেল্পার বিবরণ পেজ')], default='all', max_length=20)),
                ('position', models.CharField(choices=[('home_hero', 'হোম হিরো (শীর্ষে)'), ('home_bottom', 'হোম নিচে'), ('helpers_top', 'হেল্পার তালিকা শীর্ষে'), ('helpers_bottom', 'হেল্পার তালিকা নিচে'), ('detail_top', 'হেল্পার বিবরণ শীর্ষে'), ('detail_bottom', 'হেল্পার বিবরণ নিচে'), ('footer', 'ফুটারে')], default='home_bottom', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/', verbose_name='ছবি')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name='ভিডিও (mp4/webm)')),
                ('video_url', models.URLField(blank=True, verbose_name='ভিডিও URL (YouTube/Vimeo)')),
                ('redirect_url', models.URLField(blank=True, verbose_name='রিডিরেক্ট লিংক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('show_close_button', models.BooleanField(default=True, verbose_name='ক্লোজ বাটন দেখাবে')),
                ('auto_close_seconds', models.PositiveIntegerField(default=10, help_text='0 = ক্লোজ হবে না', verbose_name='অটো ক্লোজ (সেকেন্ড)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='শুরু তারিখ')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='শেষ তারিখ')),
                ('impressions_limit', models.PositiveIntegerField(blank=True, help_text='কতবার দেখানো হবে', null=True, verbose_name='ইম্প্রেশন লিমিট')),
                ('impressions_count', models.PositiveIntegerField(default=0, verbose_name='বর্তমান ইম্প্রেশন')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='প্রায়োরিটি (উচ্চ = আগে দেখাবে)')),
                ('display_duration', models.PositiveIntegerField(default=0, help_text='0 = সবসময় দেখাবে', verbose_name='প্রদর্শন সময় (সেকেন্ড)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপন',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.ad')),
            ],
            options={
                'verbose_name': 'এড ক্লিক',
                'verbose_name_plural': 'এড ক্লিক',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.ad')),
            ],
            options={
                'verbose_name': 'এড ইম্প্রেশন',
                'verbose_name_plural': 'এড ইম্প্রেশন',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
