# Generated by Django 6.0.5 on 2026-05-10 02:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('user', 'সাধারণ ব্যবহারকারী'), ('helper', 'হেল্পার')], default='user', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('division', models.CharField(blank=True, choices=[('dhaka', 'ঢাকা'), ('chittagong', 'চট্টগ্রাম'), ('rajshahi', 'রাজশাহী'), ('khulna', 'খুলনা'), ('barisal', 'বরিশাল'), ('sylhet', 'সিলেট'), ('rangpur', 'রংপুর'), ('mymensingh', 'ময়মনসিংহ')], max_length=20)),
                ('district', models.CharField(blank=True, choices=[('dhaka', 'ঢাকা'), ('faridpur', 'ফরিদপুর'), ('gazipur', 'গাজীপুর'), ('gopalganj', 'গোপালগঞ্জ'), ('jamalpur', 'জামালপুর'), ('kishoreganj', 'কিশোরগঞ্জ'), ('madaripur', 'মাদারীপুর'), ('manikganj', 'মানিকগঞ্জ'), ('munshiganj', 'মুন্সিগঞ্জ'), ('narayanganj', 'নারায়ণগঞ্জ'), ('narsingdi', 'নরসিংদী'), ('netrokona', 'নেত্রকোণা'), ('rajbari', 'রাজবাড়ী'), ('shariatpur', 'শরীয়তপুর'), ('sherpur', 'শেরপুর'), ('tangail', 'টাঙ্গাইল'), ('bandarban', 'বান্দরবন'), ('brahmanbaria', 'ব্রাহ্মণবাড়ীয়া'), ('chandpur', 'চাঁদপুর'), ('chittagong', 'চট্টগ্রাম'), ('comilla', 'কুমিল্লা'), ('cox_bazar', 'কক্সবাজার'), ('feni', 'ফেনী'), ('khagrachari', 'খাগড়াছড়ি'), ('lakshmipur', 'লক্ষ্মীপুর'), ('noakhali', 'নোয়াখালী'), ('rangamati', 'রাঙ্গামাটি'), ('bogra', 'বগুড়া'), ('chapainawabganj', 'চাপাই নবাবগঞ্জ'), ('jaipurhat', 'জয়পুরহাট'), ('naogaon', 'নওগাঁ'), ('natore', 'নাটোর'), ('pabna', 'পাবনা'), ('rajshahi', 'রাজশাহী'), ('sirajganj', 'সিরাজগঞ্জ'), ('bagerhat', 'বাগেরহাট'), ('chuadanga', 'চুয়াডাঙ্গা'), ('jessore', 'যশোর'), ('jhenaidah', 'ঝিনাইদহ'), ('khulna', 'খুলনা'), ('kustia', 'কুষ্টিয়া'), ('magura', 'মাগুরা'), ('meherpur', 'মেহেরপুর'), ('narail', 'নড়াইল'), ('satkhira', 'সাতক্ষীরা'), ('barguna', 'বরগুনা'), ('barisal', 'বরিশাল'), ('bhola', 'ভোলা'), ('jhalokati', 'ঝালকাঠী'), ('patuakhali', 'পটুয়াখালী'), ('pirojpur', 'পিরোজপুর'), ('habiganj', 'হবিগঞ্জ'), ('moulvibazar', 'মৌলভীবাজার'), ('sunamganj', 'সুনামগঞ্জ'), ('sylhet', 'সিলেট'), ('dinajpur', 'দিনাজপুর'), ('gaibandha', 'গাইবান্ধা'), ('kurigram', 'কুড়িগ্রাম'), ('lalmonirhat', 'লালমনিরহাট'), ('nilphamari', 'নীলফামারী'), ('panchagarh', 'পঞ্চগড়'), ('rangpur', 'রংপুর'), ('thakurgaon', 'ঠাকুরগাঁও'), ('jamalpur', 'জামালপুর'), ('mymensingh', 'ময়মনসিংহ'), ('netrokona', 'নেত্রকোণা'), ('Sherpur', 'শেরপুর')], max_length=30)),
                ('upazila', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_types', models.CharField(help_text='Comma-separated service types', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'উপলব্ধ'), ('busy', 'ব্যস্ত'), ('unavailable', 'অনুপলব্ধ')], default='unavailable', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short description in Bangla')),
                ('national_id_number', models.CharField(blank=True, max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to='accounts.userprofile')),
            ],
        ),
    ]
