# Generated by Django 6.0.5 on 2026-05-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_address',
            field=models.CharField(blank=True, help_text='বাড়ি/রোড/ব্লক নম্বর', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, help_text='ল্যান্ডমার্ক (ঐচ্ছিক)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_type',
            field=models.CharField(blank=True, choices=[('village', 'গ্রাম'), ('city', 'শহর'), ('area', 'এলাকা'), ('mohalla', 'মহল্লা'), ('para', 'পাড়া'), ('ward', 'ওয়ার্ড'), ('union', 'ইউনিয়ন')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village_city_area',
            field=models.CharField(blank=True, help_text='গ্রাম/শহর/এলাকার নাম', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='upazila',
            field=models.CharField(blank=True, choices=[('dhaka_sadar', 'ঢাকা সদর'), ('savar', 'সাভার'), ('dohar', 'দোহার'), ('keraniganj', 'কেরানীগঞ্জ'), ('faridpur_sadar', 'ফরিদপুর সদর'), ('bhanga', 'ভাঙ্গা'), ('boalmari', 'বোয়ালমারী'), ('salibada', 'সালিবাদা'), ('charbhadrasan', 'চরভদ্রাসন'), ('madarchar', 'মাদারচর'), ('gazipur_sadar', 'গাজীপুর সদর'), ('tongi', 'টঙ্গী'), ('sreepur', 'শ্রীপুর'), ('kaliganj', 'কালীগঞ্জ'), ('kapasia', 'কাপাসিয়া'), ('gopalganj_sadar', 'গোপালগঞ্জ সদর'), ('kashiani', 'কাশীয়ানী'), ('tungipara', 'তুংগীপারা'), ('gopalganj_s', 'গোপালগঞ্জ সদর'), ('kotalipara', 'কোটালীপাড়া'), ('jamalpur_sadar', 'জামালপুর সদর'), ('bhitagada', 'ভিতরগড়'), ('dewa', 'দেওয়ানগঞ্জ'), ('bakshiganj', 'বকশীগঞ্জ'), ('melandaha', 'মেলান্দহ'), ('islampur', 'ইসলামপুর'), ('kishoreganj_sadar', 'কিশোরগঞ্জ সদর'), ('hossainpur', 'হোসেনপুর'), ('pakundia', 'পাকুন্দিয়া'), ('katiadi', 'কাটিয়াদী'), ('bhairab', 'ভাইরাব'), ('tarail', 'তারাইল'), ('madaripur_sadar', 'মাদারীপুর সদর'), ('rajoir', 'রাজৈর'), ('kalkini', 'কালকিনি'), ('sibchar', 'শিবচর'), ('manikganj_sadar', 'মানিকগঞ্জ সদর'), ('daulatdia', 'দৌলতদিয়া'), ('harirampur', 'হরিরামপুর'), ('saturia', 'সাটুরিয়া'), ('ghior', 'ঘিওর'), ('munshiganj_sadar', 'মুন্সিগঞ্জ সদর'), ('sreenagar', 'শ্রীনগর'), ('serajdikhan', 'সিরাজদিখান'), ('lauhajang', 'লাউযাঙ্গা'), ('tinari', 'তিনারী'), ('narayanganj_sadar', 'নারায়ণগঞ্জ সদর'), ('siddirganj', 'সিদ্ধিরগঞ্জ'), ('araihazar', 'আড়াইহাজার'), ('bandar', 'বন্দর'), ('sonargaon', 'সোনারগাঁ'), ('narsingdi_sadar', 'নরসিংদী সদর'), ('belabo', 'বেলাবো'), ('monohardi', 'মনোহরদী'), ('narsingdi_s', 'নরসিংদী'), ('shibpur', 'শিবপুর'), ('palash', 'পলাশ'), ('netrokona_sadar', 'নেত্রকোণা সদর'), ('dhobaura', 'ধুবাউড়া'), ('kalmakanda', 'কলমাকান্দা'), ('purobi', 'পুরবী'), ('dakhin_sunamganj', 'দক্ষিণ সুনামগঞ্জ'), ('rajbari_sadar', 'রাজবাড়ী সদর'), ('baliakandi', 'বালিয়াকান্দি'), ('kalukhali', 'কালুখালী'), ('pangsha', 'পাঙ্গশা'), ('shariatpur_sadar', 'শরীয়তপুর সদর'), ('naria', 'নড়াইল'), ('jajira', 'জাজিরা'), ('bhedarganj', 'ভেদাঙ্গা'), ('damurhuda', 'দামুড়হুদা'), ('sherpur_sadar', 'শেরপুর সদর'), ('nokla', 'নকলা'), ('sribordi', 'শ্রীবরদী'), ('jhenigati', 'ঝিনাইগাতী'), ('tangail_sadar', 'টাঙ্গাইল সদর'), ('sakhipur', 'সখিপুর'), ('basail', 'বাসাইল'), ('dhanbari', 'ধানবাড়ী'), ('gopalganj', 'গোপালগঞ্জ'), ('madhupur', 'মধুপুর'), ('chittagong_sadar', 'চট্টগ্রাম সদর'), ('pahartali', 'পাহাড়তলী'), ('banskali', 'বাঁশখালী'), ('sitakunda', 'সীতাকুণ্ড'), ('rangunia', 'রাঙ্গুনিয়া'), ('hathazari', 'হাটহাজারী'), ('comilla_sadar', 'কুমিল্লা সদর'), ('chandina', 'চন্দিনা'), ('daudkandi', 'দাউদকান্দি'), ('laksam', 'লাকসাম'), ('nangalkot', 'নাঙ্গলকোট'), ('chadbogram', 'চাঁচড়া'), ('cox_bazar_sadar', 'কক্সবাজার সদর'), ('cox_bazar_s', 'কক্সবাজার'), ('moisa', 'মহেশখালী'), ('chakaria', 'চাকমা'), ('ukhiya', 'উখিয়া'), ('noakhali_sadar', 'নোয়াখালী সদর'), ('companiganj', 'কোম্পানীগঞ্জ'), ('begumganj', 'বেগমগঞ্জ'), ('hatiya', 'হাতিয়া'), ('suvanga', 'সুবর্ণচর'), ('feni_sadar', 'ফেনী সদর'), ('feni_s', 'ফেনী'), ('paris', 'পরশুরাম'), ('daganbhuiyan', 'দাগনভূঁইয়া'), ('rajshahi_sadar', 'রাজশাহী সদর'), ('rajshahi_c', 'রাজশাহী'), ('paba', 'পবা'), ('durgapur', 'দুর্গাপুর'), ('bagmara', 'বাগমারা'), ('bogra_sadar', 'বগুড়া সদর'), ('bogra_s', 'বগুড়া'), ('shariakandi', 'শার্যকান্দি'), ('kahaloo', 'কাহলো'), ('sariakandi', 'সারিয়াকান্দি'), ('pabna_sadar', 'পাবনা সদর'), ('pabna_s', 'পাবনা'), ('ishwardi', 'ঈশ্বরদী'), ('sanitoria', 'সানোহার'), ('sujanagar', 'সুজানগর'), ('naogaon_sadar', 'নওগাঁ সদর'), ('naogaon_s', 'নওগাঁ'), ('manda', 'মান্দা'), ('niamatpur', 'নিয়ামতপুর'), ('badalgachi', 'বদলগাছী'), ('khulna_sadar', 'খুলনা সদর'), ('khulna_c', 'খুলনা'), ('ditto', 'দিঘলিয়া'), ('phultala', 'ফুলতলা'), ('rupsha', 'রূপসা'), ('jessore_sadar', 'যশোর সদর'), ('jessore_s', 'যশোর'), ('jessore_t', 'যশোর'), ('bagherpara', 'বাঘেরপাড়া'), ('chungram', 'চৌগাছা'), ('satkhira_sadar', 'সাতক্ষীরা সদর'), ('satkhira_s', 'সাতক্ষীরা'), ('kalaroa', 'কলারোয়া'), ('tamil', 'তালা'), ('asashuni', 'আশাশুনি'), ('barisal_sadar', 'বরিশাল সদর'), ('barisal_c', 'বরিশাল'), (' Bakerganj', 'বাকেরগঞ্জ'), ('gournadi', 'গৌরনদী'), ('baberhat', 'বাবুরহাট'), ('bhola_sadar', 'ভোলা সদর'), ('bhola_s', 'ভোলা'), ('char_fasson', 'চরফসাদ'), ('monpura', 'মনপুরা'), ('lalmohan', 'লালমোহন'), ('sylhet_sadar', 'সিলেট সদর'), ('sylhet_c', 'সিলেট'), ('balaganj', 'বালাগঞ্জ'), ('beanibazar', 'বেয়ানবাজার'), ('golapganj', 'গোলাপগঞ্জ'), ('moulvibazar_sadar', 'মৌলভীবাজার সদর'), ('moulvibazar_s', 'মৌলভীবাজার'), ('sreemangal', 'শ্রীমঙ্গল'), ('komolganj', 'কমলগঞ্জ'), ('rajnagar', 'রাজনগর'), ('rangpur_sadar', 'রংপুর সদর'), ('rangpur_c', 'রংপুর'), ('badarganj', 'বদরগঞ্জ'), ('gangachara', 'গঙ্গাচরা'), ('taraganj', 'তারাগঞ্জ'), ('dinajpur_sadar', 'দিনাজপুর সদর'), ('dinajpur_c', 'দিনাজপুর'), ('birganj', 'বীরগঞ্জ'), ('parbatipur', 'পার্বতীপুর'), ('biral', 'বিরল'), ('mymensingh_sadar', 'ময়মনসিংহ সদর'), ('mymensingh_c', 'ময়মনসিংহ'), ('fulpur', 'ফুলপুর'), ('muktagacha', 'মুক্তাগাছা'), ('trishal', 'ত্রিশাল')], max_length=50),
        ),
    ]
